config/routes.rb
Rails.application.routes.draw do
#signup
devise_for :users
# , controllers: {
#   registrations: 'users/registrations'
# }
# #signin
# devise_scope :user do
#   root to: "devise/sessions#new"
# end
root to: "items#index"

resources :items do
  collection do
    get 'search'
  end
 member do
  post '/carts/add_item' => 'carts#add_item'
  post '/carts/update_item' => 'carts#update_item'
  delete '/carts/delete_item' => 'carts#delete_item'
  end
end


resources :orders, only:[:index,:create,:show]
  resources :orders do
   collection do
    patch :update
  end
end


resources :tables do
   resources :carts, only:[:index,:new,:create] do
   end
    resources :purchases, only:[:new,:create] do
      collection do
        patch :update
        get :show
      end
   end
end  


end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :get_total_cost, only: [:new,:create,:update,:show]
  before_action :purchase_new, only: [:new,:update]
  
  def new
  end

  def create
    # binding.pry
    #buyerが店頭決済するとき＝ admin user が手動で決済処理するとき
    if user_signed_in?
      params[:token] = "tencho_token"
    end
    
    @purchase = Purchase.new(purchase_params)  
    if @purchase.valid? # バリデーションの結果確認
      
      #buyer がクレカ決済する
      unless user_signed_in? 
        pay_item # バリデーションパスしたら支払い
      end
      @purchase.save 
    
      #オーダーテーブルに支払い記録を反映 
      @order_purhcases = Order.where(table_id:@purchase[:table_id],purchase_id:nil)
  
      @order_purhcases.each do |order_purchase|
        order_purchase.update(purchase_id:@purchase.id)
      end
    redirect_to root_path
    end
  end
  
  def show
  end

  private
  def purchase_params
    params.require(:purchase).permit(:total_cost).merge(table_id:params[:table_id],token: params[:token])
  end
  
  def purchase_new
    @purchase = Purchase.new
  end
 

  def get_total_cost
    orders = Order.where(table_id:session[:table_id],purchase_id:nil)
    @orderObject = {
      total: 0,
      rows: []
    }
    orders.each do |order|
      item = Item.find(order[:item_id])
      @orderObject[:rows].push({
        order: order,
        item: item
      })
      @orderObject[:total]+=order[:quantity]*item[:cost]
     end
  end

  def pay_item
    Payjp.api_key = ENV['PAYJP_SECRET_KEY'] # PAYJP側に決済情報を送るのに秘密鍵が必要,かぎを入れるクラス
    Payjp::Charge.create( # 決済に必要な情報を入れるクラス
      amount: @orderObject[:total],
      card: purchase_params[:token],
      currency: 'jpy'                 # 通貨の種類（日本円）
    )
  end

end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/index.html.erb
 <%= render "devise/shared/header" %>
<div class = "new_item_container">
  <%= form_with model:@purchase,url: table_purchases_path, local: true, id: 'charge-form' do |f| %>  
  <div class= "cost-group">
    <%= f.label :total_cost,"支払い合計" %>
    <div class= "form_small_cont ">
      <%=f.number_field :total_cost, class:"cost form-control", value:@orderObject[:total],readonly:true	%> <span>円</span> </p> 
    </div>
  </div>
  <h3 class="title">クレジットカード情報入力 </h3>
  <div class= "group">
      <%= f.label :number, "カード番号" ,{class:"form_label",required: true} %>
      <%= f.text_field :number, class:"form-control", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
  </div>
  <div class= "exp-group">
  <p>有効期限</p>
    <div class= "exp-set">
      <div class= "exp">
        <div class="exp-space"><%= f.label :exp_month, "月" ,{class:"form_label ",required: true} %></div>
        <div><%= f.select :exp_month, 1..12, {include_blank: "---"}, id:"card-exp-month",class: "exp_month form-control" %></div>
      </div>
      <div class= "exp">
        <div class="exp-space"><%= f.label :exp_year, "年" ,{class:"form_label ",required: true} %></div>
        <div><%= f.select :exp_year, 20..29, {include_blank: "---"}, id:"card-exp-year",class: "exp_year form-control" %></div>
      </div>
    </div>
  </div>
  <div class= "group">
      <%= f.label :cvc, "セキュリティコード" ,{class:"form_label",required: true} %>
      <%= f.text_field :cvc, class:"form-control", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
  </div>
     <div class="item-form"><%= f.submit "支払い確定",{class:"btn btn-outline-secondary"} %></div>
   <% end %>
</div>
<div class= "table_links">
    <%=link_to 'もどる', items_path %>
</div>
<%= render "devise/shared/footer" %>

app/views/purchases/new.html.erb
<%= render "devise/shared/header" %>
<div class = "new_item_container">
  <%= form_with model:@purchase,url: table_purchases_path, local: true, id: 'charge-form' do |f| %>  
  <div class= "cost-group">
    <%= f.label :total_cost,"支払い合計" %>
    <div class= "form_small_cont ">
      <%=f.number_field :total_cost, class:"cost form-control", value:@orderObject[:total],readonly:true	%> <span>円</span> </p> 
    </div>
  </div>
  <h3 class="title">クレジットカード情報入力 </h3>
  <div class= "group">
      <%= f.label :number, "カード番号" ,{class:"form_label",required: true} %>
      <%= f.text_field :number, class:"form-control", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
  </div>
  <div class= "exp-group">
  <p>有効期限</p>
    <div class= "exp-set">
      <div class= "exp">
        <div class="exp-space"><%= f.label :exp_month, "月" ,{class:"form_label ",required: true} %></div>
        <div><%= f.select :exp_month, 1..12, {include_blank: "---"}, id:"card-exp-month",class: "exp_month form-control" %></div>
      </div>
      <div class= "exp">
        <div class="exp-space"><%= f.label :exp_year, "年" ,{class:"form_label ",required: true} %></div>
        <div><%= f.select :exp_year, 20..29, {include_blank: "---"}, id:"card-exp-year",class: "exp_year form-control" %></div>
      </div>
    </div>
  </div>
  <div class= "group">
      <%= f.label :cvc, "セキュリティコード" ,{class:"form_label",required: true} %>
      <%= f.text_field :cvc, class:"form-control", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
  </div>
     <div class="item-form"><%= f.submit "支払い確定",{class:"btn btn-outline-secondary"} %></div>
   <% end %>
</div>
<div class= "table_links">
    <%=link_to 'もどる', items_path %>
</div>
<%= render "devise/shared/footer" %>

app/views/purchases/show.html.erb
 <%= render "devise/shared/header" %>
<div class ="order-content2" >
  <% @orderObject[:rows].each do |row|%> 
  <div class ="order-list2" >
      <div class ="order-name" >
            <p><%= row[:item][:name] %></p> 
      </div>
      <div class ="order-hoka" >      
            <p><%= row[:item][:cost] %>円 <span><%= row[:order][:quantity]%>個</span> </p> 
      </div>
    </div>
  <% end %>
  <% if @orderObject[:total] == 0 %>
    <p>支払い未の注文履歴はありません</p>
    <p class="order-space">合計
    <span id ="total"><%=@orderObject[:total]%>円</span>
    </p> 
    <div class="table_links">
    <%=link_to "もどる", items_path %>
    </div>
  <% else %>
    
    <div class="order-links">
      <p><%= link_to  "クレジット支払いへ",  new_table_purchase_path%></p> 
    </div> 
    <div class="table_links">
    店頭支払い希望の方は
    <%=link_to "もどる", items_path %>
    </div>
  <% end %>
</div>
<%= render "devise/shared/footer" %>