config/routes.rb
Rails.application.routes.draw do
#signup
devise_for :users
# , controllers: {
#   registrations: 'users/registrations'
# }
# #signin
# devise_scope :user do
#   root to: "devise/sessions#new"
# end
root to: "items#index"

resources :items do
  collection do
    get 'search'
  end
 member do
  post '/carts/add_item' => 'carts#add_item'
  post '/carts/update_item' => 'carts#update_item'
  delete '/carts/delete_item' => 'carts#delete_item'
  end
end


resources :orders, only:[:index,:create,:show]
  resources :orders do
   collection do
    patch :update
  end
end


resources :tables do
   resources :carts, only:[:index,:new,:create] do
   end
    resources :purchases, only:[:new,:create] do
      collection do
        patch :update
        get :show
      end
   end
end  


end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :items
  belongs_to :table


  with_options presence: true do
    validates :item_id
    validates :table_id
    validates :quantity
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :check_session, only:[:add_item,:update_item,:delete_item]

   def index
    carts = Cart.where(table_id: session[:table_id])
    if carts.present?
      @sets = []
      carts.each do |cart|
        item = Item.find(cart[:item_id])
        @sets.push({
          item: item,
          quantity: cart[:quantity]
        })
      end
    end
   end
   
   #table登録と同時にカートをつくる(item_id= null)
   def create
   session[:table_id] = params[:table][:id]
   redirect_to items_path
   end

  # カートへ を押した時のアクション
   def add_item
    @carts = Cart.find_by(table_id: session[:table_id], item_id:params[:id]) #同じカートアイテムがないか探しておく
    if @carts.present? 
      @carts[:quantity]+= params[:quantity].to_i 
      @carts.save
    else
      @carts = Cart.create(table_id:session[:table_id], item_id:params[:id],quantity:params[:quantity])
    end
     redirect_to table_carts_path(session[:table_id])
   end

  # カート詳細画面から、「更新」を押した時のアクション
  def update_item
    @cart = Cart.find_by(table_id: session[:table_id], item_id: params[:id])
    @cart.update(quantity: params[:quantity].to_i)
    redirect_to  table_carts_path(@cart.table_id)
  end

 # カート詳細画面から、「削除」を押した時のアクション
  def delete_item
      @cart = Cart.find_by(table_id:session[:table_id], item_id:params[:id])
      unless @cart.blank?
        @cart.destroy
      end
      redirect_to table_carts_path(@cart.table_id)
  end

  def check_session
    if session[:table_id] == nil
     redirect_to  new_table_path
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<%= render "devise/shared/header" %>

<div class ="item-inner" >
  <%if @sets.blank? %>
    <p>現在カートの中は空です</p>
    <%=link_to 'もどる', root_path %>
  <% else %>
    <p>カートの中は以下のメニューです</p>
<div class ="show-cart-inner" >
    <% @sets.each do |set| %>
    <div class="list">
      <div>    
        <%= image_tag set[:item].image.variant(resize: '200x200'), class: "item-img"%>
      </div>
      <div class="item-info">
        <p><%= set[:item][:name] %></p>
        <div class="show-cart-quantity">
          <p><%= "#{set[:item][:cost]}円" %>
          <p><%= "#{set[:quantity]}個" %></p>
        </div>
      </div>
      
     
      <div class="show-cart-form">
        <%= form_with url: carts_update_item_item_path(set[:item][:id]), local: true do |f| %>
          <%= f.label :quantity, '個数' %>
          <%= f.select("quantity", [1,2,3,4,5], class:'form-select form-select-sm')%>
          <%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md" do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus" viewBox="0 0 16 16">
              <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9V5.5z"/>
              <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
            </svg>
          <% end %>
          <%= link_to carts_delete_item_item_path(set[:item][:id]), method: :delete do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
          <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
          </svg>
          <%end %>
        <%end %>
      </div>
    </div>
    <% end %>


    <div class="item-form">
      <h4><%=link_to "オーダー確定", orders_path ,method: :post%> </h4>
      <%=link_to '追加で選ぶ', root_path %>
    </div>
  <% end %>
 </div>
<%= render "devise/shared/footer" %>



 