config/routes.rb
Rails.application.routes.draw do
#signup
devise_for :users
# , controllers: {
#   registrations: 'users/registrations'
# }
# #signin
# devise_scope :user do
#   root to: "devise/sessions#new"
# end
root to: "items#index"

resources :items do
  collection do
    get 'search'
  end
 member do
  post '/carts/add_item' => 'carts#add_item'
  post '/carts/update_item' => 'carts#update_item'
  delete '/carts/delete_item' => 'carts#delete_item'
  end
end


resources :orders, only:[:index,:create,:show]
  resources :orders do
   collection do
    patch :update
  end
end


resources :tables do
   resources :carts, only:[:index,:new,:create] do
   end
    resources :purchases, only:[:new,:create] do
      collection do
        patch :update
        get :show
      end
   end
end  


end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  # before_action :authenticate_user!
  before_action :clean_table, only:[:create]

 def index  
  @tables = Table.all
 end
 
  def new
   @tables = Table.all
   unless user_signed_in?
      render new_table_path
   else

      if @tables.present?
          redirect_to tables_path
      else
          render :create
      end
    end
  end

  def create 
    @tables = []
    if params[:table_quantity_id].present?
      num = params[:table_quantity_id].to_i
      num.times do
        @tables.push(Table.create!)
      end
      redirect_to tables_path
    else
      redirect_to new_table_path
    end
  end
  
  def clean_table
  @tables = Table.all
   #テーブルの数numだけレコードを作る
    if @tables.present?
       @tables.destroy_all
       ActiveRecord::Base.connection.execute('ALTER TABLE tables AUTO_INCREMENT = 1')
      #もしテーブルがすでにあるなら全て削除してからid１から作り直す
    end
  end


 
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/create.html.erb
<%= render "devise/shared/header" %>
<div class="table_info">
  <p>現在登録中のテーブルはありません</p>
  <p>テーブルの数を選択してください <span >(必須)</span> </p>
  <div class="table-create-form"> 
   <%=form_with  url: tables_path, local: true do |f| %> 
     <p> <%= f.collection_select(:table_quantity_id, TableQuantity.all, :id, :id, {},{:style => 'width: 80px',class: 'form-control select_css_tag'}) %></p>
     <p class="input-space"><%= f.submit "登録する" ,{class:"btn btn-outline-secondary"}%></p>
  <%end%>
 </div>
</div>
<div class="table_links">
  <%=link_to 'もどる', items_path %></p>
</div>
<%= render "devise/shared/footer" %>

app/views/tables/index.html.erb
<%= render "devise/shared/header" %>
<% if @tables.blank? %>
    <div class = 'table_info2'>
        <p>現在登録中のテーブルはありません。</p>
    </div>
<% else %>
<div class="table_info">
    使用中のテーブル
    <div class="table_ids">
        <ul>
          <% @tables.each do |table|%>
           <li><%= table.id %></li>
          <%end%>
        </ul>
    </div>
  </div>
  <div class="table_purchase_input">
      会計するテーブル
      <%=form_with model: @tables,url: order_path(@tables.ids),local: true, method: :get do |f| %>
      <p><%= f.collection_select(:id, @tables,:id,:id,{selected: 1}, {:style => 'width: 80px',class: 'form-control', required: true }) %></p>
  
      <p><%= f.submit "会計へ" ,{class:"btn btn-outline-secondary"}%></p>
      <% end %>
  </div>
<% end %>
<div class="table_links">
  <p><%=link_to 'テーブル再登録',tables_path, method: :post%></p>
  <%=link_to 'もどる', items_path %>
</div>
<%= render "devise/shared/footer" %>

app/views/tables/new.html.erb
<%= render "devise/shared/header" %>
    <div  class="table_info">
      <% if @tables.present? %>
        <p>使用するテーブルを選択してください <span>（必須）</span> </p>
        <div class="show-cart-form">   
          <%=form_with model:@tables, url: table_carts_path(@tables.ids),local: true do |f| %>
            <div > <%= f.collection_select(:id, @tables, :id, :id,{},class: "form-control input-sm")%></div>
            <div class="input-space"><%= f.submit "決定",{class:"btn btn-outline-secondary"} %></div>
          <% end %>
        </div>
      <% elsif @tables.empty? %>    
       <div  class="table_info">テーブル準備中</div>
     <% end %>
  </div>
<div class="table_links">
  <%=link_to 'もどる', items_path %>
</div>
<%= render "devise/shared/footer" %> 