config/routes.rb
Rails.application.routes.draw do
#signup
devise_for :users
# , controllers: {
#   registrations: 'users/registrations'
# }
# #signin
# devise_scope :user do
#   root to: "devise/sessions#new"
# end
root to: "items#index"

resources :items do
  collection do
    get 'search'
  end
 member do
  post '/carts/add_item' => 'carts#add_item'
  post '/carts/update_item' => 'carts#update_item'
  delete '/carts/delete_item' => 'carts#delete_item'
  end
end


resources :orders, only:[:index,:create,:show]
  resources :orders do
   collection do
    patch :update
  end
end


resources :tables do
   resources :carts, only:[:index,:new,:create] do
   end
    resources :purchases, only:[:new,:create] do
      collection do
        patch :update
        get :show
      end
   end
end  


end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :user
  belongs_to_active_hash :genre
  has_one_attached :image, dependent: true

  with_options presence: true do
  validates :name
  validates :cost
  validates :image
  end
  
  with_options presence: true, numericality: { other_than: 1 } do
    validates :genre_id
  end
                        
  validates :cost, numericality: { with: /\A[0-9]+\z/, message: 'は半角数字で入力してください' }
  validates :cost, inclusion: { in: 300..99_999, message: 'は300~99.999円までの範囲で入力してくだい' }
 


 def self.search(keyword)
    if search != ""
      Item.where('name LIKE(?)')
      @items = Item.where(:genre_id)
    else
      Item.all
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except:[:index,:show]
  before_action :set_items, only: [:edit, :show, :update, :destroy]

  def index
    @items = Item.all
    unless params[:keyword] == "1" || params[:keyword] == nil
       @items = Item.where(genre_id: (params[:keyword])).order(created_at: :desc)
    end
    @carts = Cart.find_by(table_id: session[:table_id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.valid?
      @item.save
      return redirect_to root_path
    end
    render 'new'
  end

  def show
   @cart = Cart.new
  end

  def edit
  end

  def update
    @item.update(item_params)
    if @item.update(item_params)
      redirect_to "/"    
    else
      render :edit
    end
  end

  def destroy
     if  current_user.id == @item.user_id 
          @item.destroy
          redirect_to root_path
     elsif current_user.host_name.present?
         @cart_item = CartItem.find_by(params[:id]) 
         @cart = Cart.find_by(cart_item_id:@cart_item.id)
        
        if @cart.present?
          @cart.destroy
        else @cart_item.present? 
          @cart_item.delete
          @item.destroy
          redirect_to root_path
        end
      end
  end

  private
  def item_params
    params.require(:item).permit(
      :image, :name, :description, :genre_id, :cost).merge(user_id: current_user.id)
  end

  def set_items
    @item = Item.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%= render "devise/shared/header" %>
<div class = "new_item_container">
  <h3>メニュー編集</h3>
  <%= form_with model:@item, url: item_path,method: :put,local: true do |f| %>
    <div class= "group">
            <%= f.label :image, "画像" ,{class:"form_label"} %>
            <div class= "form_cont"> 
                <%= f.file_field :image ,required: true %>
            </div>
      </div>
      <div class = "group">
          <%= f.label :name, "メニュー名" ,{class:"form_label",required: true} %>
          <div class= "form_cont">
              <%= f.text_area :name, placeholder:"半熟あつあつのたこやき", maxlength:"30", rows:"1",class:"form-control" %>
              <p> 20文字まで</p>
            </div>
      </div>
      <div class = "group">
          <p> ひとこと紹介</p>
            <div class= "form_cont">
              <%= f.text_area :description,rows:"5" ,maxlength:"80",class:"form-control" %>
              <p> 80文字まで</p>
            </div>
      </div>
      <div class = "group">
          <%= f.label :genre_id, "カテゴリー" ,{class:"form_label"} %>
            <div class= "form_cont">
              <%= f.collection_select(:genre_id, Genre.all, :id, :name, {},{class: "form-control input-sm"}) %>
            </div> 
      </div> 
      <div class = "group">
          <%= f.label :cost, "価格" ,{class:"form_label"} %>
          <div class= "form_small_cont">
              <%= f.text_field :cost, placeholder:"500",class:"cost form-control",required: true%>&emsp;<span>円</span>
          </div>
      </div>  
  <%= f.submit "編集完了",{class:"btn btn-outline-secondary"} %>
  <% end %>
</div>
<div class= "table_links">
   <%=link_to 'もどる', items_path %>
</div>
 <%= render "devise/shared/footer" %>

app/views/items/index.html.erb
<%= render "devise/shared/header" %>
<div class="item-form">
 <h3>Menu</h3> 
 <div class="search-form">
 <%= form_with(url: items_path, local: true, method: :get) do |form| %>
    <p><%=select_tag "keyword" ,options_from_collection_for_select(Genre.all, "id", "name", "1"),{:style => 'width: 150px',class: 'form-control select_css_tag'}%>
    <p><%= form.submit "検索", {class:"btn btn-outline-secondary"} %></p>
  <% end %> 
  </div >
</div >
<div class ="item-content" >
   <ul class ="item-inner">
    <% @items.each do |item|%>
      <li class='list'>
        <%= link_to item_path(item.id)  do %>
          <div class='item-img-content'>
            <%= image_tag item.image.variant(resize: '200x200'), class: "item-img" %>
          </div>

          <div class='item-info'>
            <p><%= item.name %></p>
            <div ><%= item.cost %>円<br></div>
          </div>
          <div class = "ItemIcons">
            <% if  user_signed_in? && current_user.id == item.user_id %>
              <%= link_to edit_item_path(item.id) do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
              </svg>
              <% end %>

                <%= link_to item_path(item.id), method: :delete do %> 
                
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
               </svg>
            <% end %>
            </div>

          <% end %>
         <% end %>
      </li>
    <% end %>
    <% if @items.empty?%>
      <p>  選択のジャンルにメニューはありません。</p>
    <% end %>
  </ul>
</div>
<%= render "devise/shared/footer" %>

app/views/items/new.html.erb
<%= render "devise/shared/header" %>
<div class = "new_item_container">
 <h3>新メニュー登録</h3>
  <%= form_with model:@item, url: items_path, local: true do |f| %>
    <div class= "group">
          <%= f.label :image, "画像" ,{class:"form_label"} %>
          <div class= "form_cont"> 
              <%= f.file_field :image ,required: true%>
          </div>
    </div>
    <div class = "group">
         <%= f.label :name, "メニュー名" ,{class:"form_label",required: true} %>
        <div class= "form_cont">
            <%= f.text_area :name, placeholder:"苺のショートケーキ", maxlength:"30", rows:"1",class:"form-control" %>
            <p> 20文字まで</p>
          </div>
    </div>
    <div class = "group">
         <p> ひとこと紹介</p>
          <div class= "form_cont">
            <%= f.text_area :description, placeholder:"旬のおいしい苺をたくさん使用しました。",rows:"5" ,maxlength:"80",class:"form-control" %>
            <p> 80文字まで</p>
          </div>
    </div>
    <div class = "group">
         <%= f.label :genre_id, "カテゴリー" ,{class:"form_label"} %>
          <div class= "form_cont">
            <%= f.collection_select(:genre_id, Genre.all, :id, :name, {},{class: "form-control input-sm"}) %>
          </div> 
    </div> 
    <div class = "group">
        <%= f.label :cost, "価格" ,{class:"form_label"} %>
        <div class= "form_small_cont">
            <%= f.text_field :cost, placeholder:"500",class:"cost form-control",required: true%>&emsp;<span>円</span>
        </div>
     </div>
  <%= f.submit "登録する",{class:"btn btn-outline-secondary"} %>
  <% end %>
</div>

<div class= "table_links">
    <%=link_to 'もどる', items_path %>
</div>
<%= render "devise/shared/footer" %>

app/views/items/show.html.erb
<%= render "devise/shared/header" %>
<div class ="item-content" >
<div class="item-inner">
   <div class="list">
      <div>
        <%= image_tag @item.image.variant(resize: '200x200') ,class: "item-img" %>
      </div>
      <div class="item-info">
        <p ><%= @item.name %></p>
        <p ><%= @item.cost %>円<br></p>
      </div>
   </div>   
   <p class="item-form"><%= @item.description %></p>
  
  
    <% unless user_signed_in? %>
      <%= form_with url: carts_add_item_item_path(@item.id),local: true do |f| %>
        <%= f.label :quantity, '個数' %>
        <%= f.select :quantity, [1,2,3,4,5], { include_blank: '選択してください', required: true}%>
         <%= button_tag :type => "submit", :class =>"btn btn-outline-secondary" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus" viewBox="0 0 16 16">
        <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9V5.5z"/>
        <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
      </svg>
      <% end %>
      <% end %>
    <% end %>
</div>
  <div class="table_links">
    <%=link_to 'もどる', items_path %>
  </div>
</div>

 <%= render "devise/shared/footer" %>

 